server:
  port: 8763
spring:
  application:
    name: eurekaclient
   
#配置中心手动刷新
management:
    endpoints:
        web:
            exposure:
                include: refresh,health,info,bus-refresh
spring:
    rabbitmq:
        addresses: 192.168.0.47:5673,192.168.0.72:5673
        host: 192.168.0.58
        username: admin
        password: hooenergy
        virtualHost: /
        publisherConfirms: true
